### PR TITLE
Update footer.php

### PR DESCRIPTION
**Pull request by Naidru**
iFastNet URL in Footer now goes to an affiliate link, also update the "iFast.Net" text to "iFastNet"

### CODE REVIEW

**Comment by Naidru** [comment]
I'm also wondering if I can help this project by being a contributor to it and having write access. I can easily fix any typing mistakes and doing small stuff like this which can make the Hustal project a better option.

**Comment by mahtab2003** [comment]
Ok if you really want to but don't delete anything without telling me

**Comment by Naidru** [comment]
I won't delete anything without saying anything, plus you would be able to see any changes I make

**Comment by mahtab2003** [comment]
OK you are invited to be a contributer

**Pull request closed without merging**
